version: "3.1"
services:
  detectron2:
    image: "eungbean/detectron2-vscode"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
    gpus: '"device=1"'
    # gpus: all
    # shm_size: "8gb"
    # ulimits:
    #   memlock: -1
    #   stack: 67108864
    volumes:
      - /LIG/DATASET/ADD:/home/appuser/dataset
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - PASSWORD="0924"
    ports:
      - "7100:8080"
      - "7106-7115:6006-6015"
    command: 
      - /coder/code-server
    # ipc: 
    #   - "host"